Street systems lambda
LBHackney-IT/Data-Platform pull request #1602
Opened 2024-02-20 12:52 UTC by LBHMVillalobos

New file created:
lambdas/street_systems_api_ingestion/main.py
Script to call Street System API, create dataframes and write to S3

File updated: 
terraform/etl/49-lambda-streetscene-ingestion.tf
New module and trigger have been added

2024-02-20 13:46 UTC, timburke-hackit requested changes

2024-02-20 13:46 UTC, timburke-hackit commented on terraform/etl/49-lambda-streetscene-ingestion.tf
> +    "arn:aws:lambda:eu-west-2:336392948345:layer:AWSSDKPandas-Python39:12",
replace account id with this interpolated value - the account numbers are different depending on which environment you're deploying to:

```suggestion
    "arn:aws:lambda:eu-west-2:${data.aws_caller_identity.data_platform.account_id}:layer:AWSSDKPandas-Python39:12",
```

2024-02-20 13:55 UTC, timburke-hackit commented on terraform/etl/49-lambda-streetscene-ingestion.tf
> +    "arn:aws:lambda:eu-west-2:336392948345:layer:AWSSDKPandas-Python39:12",
actually, ignore this - I've mis-remembered the stg account number and thought it was this

2024-02-20 14:07 UTC, timburke-hackit submitted a review, later dismissed

2024-02-20 14:07 UTC, timburke-hackit commented on terraform/etl/49-lambda-streetscene-ingestion.tf
> +    "arn:aws:lambda:eu-west-2:120038763019:layer:requests-2-31-0-and-httplib-0-22-0-layer:1",
```suggestion
    "arn:aws:lambda:eu-west-2:${data.aws_caller_identity.data_platform.account_id}:layer:requests-2-31-0-and-httplib-0-22-0-layer:1",
```

2024-02-20 14:07 UTC, timburke-hackit commented on terraform/etl/49-lambda-streetscene-ingestion.tf
> +    "arn:aws:lambda:eu-west-2:120038763019:layer:s3fs-2023-12-2-layer:1"
interpolate account number for different environment accounts
```suggestion
    "arn:aws:lambda:eu-west-2:${data.aws_caller_identity.data_platform.account_id}:layer:urllib3-1-26-18-layer:1",
    "arn:aws:lambda:eu-west-2:${data.aws_caller_identity.data_platform.account_id}:layer:s3fs-2023-12-2-layer:1"
```

2024-02-20 14:07 UTC, timburke-hackit commented on terraform/etl/49-lambda-streetscene-ingestion.tf
> +    "arn:aws:lambda:eu-west-2:120038763019:layer:requests-2-31-0-and-httplib-0-22-0-layer:1",
this one is the stg account id though so does need to be interpolated

2024-02-20 14:49 UTC, timburke-hackit commented on terraform/etl/49-lambda-streetscene-ingestion.tf
> +    "arn:aws:lambda:eu-west-2:${data.aws_caller_identity.data_platform.account_id}:layer:AWSSDKPandas-Python39:12",
This one was OK, 336392948345 is where the AWS managed layers live and is the same regardless of where you're deploying to - sorry my fault
```suggestion
    "arn:aws:lambda:eu-west-2:336392948345:layer:AWSSDKPandas-Python39:12",
```

2024-02-26 12:27 UTC, LBH-wgreeff approved these changes
LGTM

2024-02-26 14:09 UTC, merged